// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})

export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();
  autoresForm: string = "";
  editoras: Array<Editora> = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split("\n");
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl("/lista");
    });
  }
}

<main class="container mt-4">
    <h2 class="mb-4 text-center">Dados do Livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      
      <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo</label>
        <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      
      <div class="mb-3">
        <label for="editora" class="form-label">Editora</label>
        <select id="editora" class="form-select" [(ngModel)]="livro.codEditora" name="editora" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
      
      <div class="mb-3">
        <label for="autores" class="form-label">Autores <small class="text-body-secondary">(1 por linha)</small></label>
        <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary btn-block">Salvar Dados</button>
    </form>
  </main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from "next";
import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import ControleEditora from "@/classes/controle/ControleEditora";
import Livro from "@/classes/modelo/Livro";
import { Menu } from "@/componentes/Menu";
import ControleLivro from "@/classes/controle/ControleLivros";

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivro();

const LivroDados: NextPage = () => {
    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome
    }))

    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0]?.value);

    const router  = useRouter();

    const tratarCombo = (evento: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(evento.target.value));
    }
    
    const incluir = async (evento: React.FormEvent<HTMLFormElement>) => {
        evento.preventDefault();

        const novoLivro: Livro = {
            codigo: "",
            titulo,
            resumo,
            autores: autores.split("\n"),
            codEditora
        }

        await controleLivros.incluir(novoLivro).then(() => {
            try {
                router.push("/LivroLista");
            }
            catch (erro) {
                console.log(`Erro ao incluir livro: ${erro}`);
            }
            
        });
    }

    return (
        <div className="container-fluid">
            <Head>
                <title>Loja Next | Cadastro de Livro</title>
            </Head>
            <Menu />
            <main className="main m-3">
                <h1 className="h1 mb-5 mt-4">Cadastro de Livro</h1>
                <form onSubmit={incluir}>
                    <div className="form-group">
                        <label htmlFor="titulo">Título</label>
                        <input type="text" id="titulo" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                    </div>

                    <div className="form-group">
                        <label htmlFor="resumo">Resumo</label>
                        <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
                    </div>

                    <div className="form-group">
                        <label htmlFor="autores">Autores (um por linha)</label>
                        <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
                    </div>

                    <div className="form-group">
                        <label htmlFor="editora">Editora</label>
                        <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo}>
                            { opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>
                                    { opcao.text }
                                </option>
                            )) }
                        </select>
                    </div>

                    <button type="submit" className="btn btn-primary mt-3">Incluir Livro</button>
                </form>
            </main>
        </div>
    );
}

export default LivroDados;
