// clientes/livros-react/src/LivroDados.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

const LivroDados = () => {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();

    const opcoes = controleEditora.getEditoras().map(
        (editora) => ({
            value: editora.codEditora,
            text: editora.nome,
        })
    );

    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes?.value || 0);

    const navigate = useNavigate();

    const tratarCombo = (evento) => {
        setCodEditora(Number(evento.target.value));
    }

    const incluir = (evento) => {
        evento.preventDefault();

        const novoLivro = {
            codigo: "",
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n"),
            codEditora: codEditora
        }

        controleLivro.incluir(novoLivro).then(() => navigate("/"));
    }

    return (        
        <main className="p-4">
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>

                <div className="mb-3">
                    <label className="form-label">Título</label>
                    <input type="text" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)}/>
                </div>

                <div className="mb-3">
                    <label className="form-label">Resumo</label>
                    <textarea className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)}/>
                </div>

                <div className="mb-3">
                    <label className="form-label">Editora</label>
                    <select className="form-select" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>

                <div className="mb-3">
                    <label className="form-label">Autores (um por linha)</label>
                    <textarea className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)}/>
                </div>

                <button type="submit" className="btn btn-primary">Salva Dados</button>

            </form>
        </main>
    );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})

export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();
  autoresForm: string = "";
  editoras: Array<Editora> = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split("\n");
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl("/lista");
    });
  }
}

<main class="container mt-4">
    <h2 class="mb-4 text-center">Dados do Livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      
      <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo</label>
        <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      
      <div class="mb-3">
        <label for="editora" class="form-label">Editora</label>
        <select id="editora" class="form-select" [(ngModel)]="livro.codEditora" name="editora" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
      
      <div class="mb-3">
        <label for="autores" class="form-label">Autores <small class="text-body-secondary">(1 por linha)</small></label>
        <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary btn-block">Salvar Dados</button>
    </form>
  </main>
